// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfpnLQ4-npn_S1d9g62Eg32eYfj9wu7M8',
    appId: '1:318491809401:web:6e512fe183f7a4f4fe66a8',
    messagingSenderId: '318491809401',
    projectId: 'gerenciador-horas',
    authDomain: 'gerenciador-horas.firebaseapp.com',
    storageBucket: 'gerenciador-horas.firebasestorage.app',
    measurementId: 'G-Q9CH5TKYG3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB42Borv86uOmfGKezMp9xsxQ_qaLVf_G4',
    appId: '1:318491809401:android:4f4c2a1a49bd4136fe66a8',
    messagingSenderId: '318491809401',
    projectId: 'gerenciador-horas',
    storageBucket: 'gerenciador-horas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxkQOWrXqfASPe3iQMlg_Ycu_BQsnHkiA',
    appId: '1:318491809401:ios:d57e7119e9b3af35fe66a8',
    messagingSenderId: '318491809401',
    projectId: 'gerenciador-horas',
    storageBucket: 'gerenciador-horas.firebasestorage.app',
    iosBundleId: 'com.example.gerenciadorHoras',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxkQOWrXqfASPe3iQMlg_Ycu_BQsnHkiA',
    appId: '1:318491809401:ios:d57e7119e9b3af35fe66a8',
    messagingSenderId: '318491809401',
    projectId: 'gerenciador-horas',
    storageBucket: 'gerenciador-horas.firebasestorage.app',
    iosBundleId: 'com.example.gerenciadorHoras',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfpnLQ4-npn_S1d9g62Eg32eYfj9wu7M8',
    appId: '1:318491809401:web:f6ba337970e0fe62fe66a8',
    messagingSenderId: '318491809401',
    projectId: 'gerenciador-horas',
    authDomain: 'gerenciador-horas.firebaseapp.com',
    storageBucket: 'gerenciador-horas.firebasestorage.app',
    measurementId: 'G-D2BZJCBGMR',
  );
}
